# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Biko < Formula
  desc "CLI tool to jump to your browser directly"
  homepage "https://github.com/KeisukeYamashita/biko"
  version "0.0.20"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/KeisukeYamashita/biko/releases/download/v0.0.20/biko_0.0.20_darwin_amd64.tar.gz"
      sha256 "796347ee78001827d5ae0546a728c27a6589a9743a8ebdc59923649f92a165e7"
    end
    if Hardware::CPU.arm?
      url "http://github.com/KeisukeYamashita/biko/releases/download/v0.0.20/biko_0.0.20_darwin_arm64.tar.gz"
      sha256 "338670da7da9bcd3dd92009db3165f347686275874ea826d4a851216b23d33b3"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://github.com/KeisukeYamashita/biko/releases/download/v0.0.20/biko_0.0.20_linux_amd64.tar.gz"
      sha256 "072982538ab331b14cc4d4d4eb7a4a3df822720f68c2265774eea921332cc308"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/KeisukeYamashita/biko/releases/download/v0.0.20/biko_0.0.20_linux_arm64.tar.gz"
      sha256 "8c7033a47d759dc66f0a20ff00ae491e978dcc95bf14b46e334d068fc0a35c56"
    end
  end

  def install
    bin.install "biko"
  end

  test do
    system "#{bin}/biko --version"
  end
end
