# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Biko < Formula
  desc "CLI tool to jump to your browser directly"
  homepage "https://github.com/KeisukeYamashita/biko"
  version "0.0.19"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "http://github.com/KeisukeYamashita/biko/releases/download/v0.0.19/biko_0.0.19_darwin_amd64.tar.gz"
      sha256 "12458dd668b6065e47497c285e49824ebc4ae194bc7d75d9351311d9a1317bdd"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "http://github.com/KeisukeYamashita/biko/releases/download/v0.0.19/biko_0.0.19_linux_amd64.tar.gz"
      sha256 "a48b52dcbd2108ce71f8df676ca594e67d9ffc68b32b3a04f121b2594795461d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "http://github.com/KeisukeYamashita/biko/releases/download/v0.0.19/biko_0.0.19_linux_arm64.tar.gz"
      sha256 "6bdd56043438c670da254d00703e522fa22519065b283e4683e631bc903aac75"
    end
  end

  def install
    bin.install "biko"
  end

  test do
    system "#{bin}/biko --version"
  end
end
