# This file was generated by GoReleaser. DO NOT EDIT.
class Biko < Formula
  desc "CLI tool to jump to your browser directly"
  homepage "https://github.com/KeisukeYamashita/biko"
  version "0.0.18"
  bottle :unneeded

  if OS.mac?
    url "http://github.com/KeisukeYamashita/biko/releases/download/v0.0.18/biko_0.0.18_darwin_amd64.tar.gz"
    sha256 "7970e34ad7d5dbdd4240d98e37d607c578df22d97e0226c7e702285ff0ef42dd"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "http://github.com/KeisukeYamashita/biko/releases/download/v0.0.18/biko_0.0.18_linux_amd64.tar.gz"
    sha256 "f27180f7556f0bcf245ef8817ac3bf3dd01f52df48502d97cea12b396d30340e"
  end

  def install
    bin.install "biko"
  end

  test do
    system "#{bin}/biko --version"
  end
end
